### ISSUE TITLE
After creating a PA request, redirect user's browser to the DM or show a modal 

### ISSUE THREAD

**Issue by CAZ-H** [roblox-dev-forum/new-member-redirect#14]
The forum should redirect the user's browser to the PA DM, or a modal window (similar to the one users see when their thread is hijacked for containing blacklisted URLs) should be shown telling them what just happened.

![image](https://user-images.githubusercontent.com/26800119/68089689-2179e500-fe31-11e9-8093-ac5f171661f4.png)

Users don't pay attention to their notifications after creating a request and are confused about why their thread is now in bulletin board, so they try to create a new one, sometimes filing 2+ PA requests.  

Currently, the user will be shown their thread in bulletin board and they'll have a notification in the top right corner from System replying to the PA DM, which is not visible enough when the user isn't paying attention, or if they have other DM notifications already.

**Comment by buildthomas** [comment]
Fixed in: https://github.com/roblox-dev-forum/post-approval
