### ISSUE TITLE
Extra setting on category that allows you to specify system response to message with extra details

### ISSUE THREAD

**Issue by buildthomas** [roblox-dev-forum/new-member-redirect#5]
This should be a category setting as textbox. Whatever you fill into the box will be sent as a reply to the message when people get redirected from that category.

For Web Bugs we could have:
> Your message has been put in review for approval for the Web Bugs category.
> 
> Please make sure it meets these guidelines: <...> Also, have you tried that the bug still occurs without any browser extensions?

For Client Bugs we could have:
> Your message has been put in review for approval for the Client Bugs category.
> 
> Please make sure it meets these guidelines: <...> Please attach a clear, minimal repro file blabla.

Maybe we can have a site setting to pick the user that the reply should be by? Or a random group of users like the DevEng plugin? (i.e. able to set "system", or from "Roblox", or from a random person in the "Post_Approval" group)

**Comment by Kampfkarren** [comment]
awesome alternative to the linter idea
